### PR TITLE
fixes, link kodi site and auto light/darkmode

### PR DESCRIPTION
**Pull request by docgalaxyblock**
Hey I just discovered your nice documentation.

While reading I noticed the two typos and on further inspection I noticed some images are missing:
- https://github.com/ironicbadger/pms-wiki/blob/main/docs/06-hardware/intel-quicksync.md?plain=1#L11-L13
- https://github.com/ironicbadger/pms-wiki/blob/main/docs/06-hardware/hdd-purchase-methodology.md?plain=1#L43
- https://github.com/ironicbadger/pms-wiki/blob/main/docs/06-hardware/hdd-purchase-methodology.md?plain=1#L63

There is a non existend FAQ section refernced [here](https://github.com/ironicbadger/pms-wiki/blob/155e614f7ad252c87037f2fdd9dc53db2ba76b13/docs/03-installation/manual-install-ubuntu.md?plain=1#L23C157-L23C260)

Note Immich at the "top 10 apps" alternatives if that is allowed since it seems to be mentioned at [episode 79](https://selfhosted.show/79?t=1418) _(just discovered the podcast and therefore did not listen to it yet)_

And added the required config lines for mkdocs-material to consider the users system/browser preferences regarding light or dark (https://github.com/ironicbadger/pms-wiki/commit/236b64eb063710e1974abc7787d76e1c0c4cb062).

---

I currently have no mkdocs-material with me therefore not tested.

Greetings from 🇩🇪

### CODE REVIEW

**Comment by ironicbadger** [comment]
awesome thanks!

**Comment by docgalaxyblock** [comment]
Hey do you have the issues in mind after merging this or should I open an issue?

**Comment by ironicbadger** [comment]
I'm confused. What issues?

**Comment by docgalaxyblock** [comment]
These ones mentioned above:

> [...] I noticed some images are missing:
> - https://github.com/ironicbadger/pms-wiki/blob/main/docs/06-hardware/intel-quicksync.md?plain=1#L11-L13
> - https://github.com/ironicbadger/pms-wiki/blob/main/docs/06-hardware/hdd-purchase-methodology.md?plain=1#L43
> - https://github.com/ironicbadger/pms-wiki/blob/main/docs/06-hardware/hdd-purchase-methodology.md?plain=1#L63
>
> There is a non existend FAQ section refernced [here](https://github.com/ironicbadger/pms-wiki/blob/155e614f7ad252c87037f2fdd9dc53db2ba76b13/docs/03-installation/manual-install-ubuntu.md?plain=1#L23C157-L23C260)

**Pull request merged**
