### PR TITLE
Create single-sign-on.md

### PR DESCRIPTION
**Pull request by mindfuucker**
As mentioned in the Discord: A guide about Vouch Proxy. I'm not a native English speaker so please check it before uploading.

### CODE REVIEW

**Comment by IronicBadger** [comment]
Thanks for writing this up - I'll want to take a stab at following the guide before merging which will be a few days at least.

**Comment by mindfuucker** [comment]
The guide has some fat to trim off, especially in the config files. I was not sure where to put the cut so I left it all in. 
Some things you might want to change:

- domain.com to example.com
- /srv/vouch directory 
- some other hardcoded values like using Jackett

**Comment by IronicBadger** [comment]
Sorry had a busy month, haven't got to this yet. Will do eventually.

**Review by inspector71 — COMMENTED** [review]
Would like to help. How do I edit?

**Pull request closed without merging**
